# Generated by Django 2.0.5 on 2018-12-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181212_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='status',
        ),
    ]
